### Loading Data

### cleaning file#1 (job_postings dataset)

In [1]:
import os
import pandas as pd
import matplotlib.pyplot as plt

notebook_dir = os.path.abspath("")
parent_dir = os.path.abspath("..")
org_dataset_path = os.path.join(parent_dir, "raw_datasets", "job_postings.csv")
df = pd.read_csv(org_dataset_path)

In [2]:
df.sample(3)

,job_id,company_id,title,max_salary,med_salary,min_salary,pay_period,formatted_work_type,location,applies,...,expiry,closed_time,formatted_experience_level,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type
4641,3693583733,3743.0,State and Local Tax Intern - Winter 2025,NaN,33.0,NaN,HOURLY,Full-time,"Houston, TX",NaN,...,1.700000e+12,NaN,NaN,NaN,1.690000e+12,rsm.wd1.myworkdayjobs.com,0,FULL_TIME,USD,BASE_SALARY
3887,3693070252,2539.0,Outside Account Executive,NaN,NaN,NaN,NaN,Full-time,"Wheeling, WV",1.0,...,1.700000e+12,NaN,Mid-Senior level,NaN,1.690000e+12,iheartmedia.wd5.myworkdayjobs.com,0,FULL_TIME,NaN,NaN
13383,3701302521,11357247.0,"Travel MedSurg RN in Durham, NC - Make $2221.4...",NaN,NaN,NaN,NaN,Part-time,"Durham, NC",NaN,...,1.700000e+12,NaN,Mid-Senior level,NaN,1.690000e+12,ctmc.contingenttalentmanagement.com,0,PART_TIME,NaN,NaN

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15886 entries, 0 to 15885
Data columns (total 26 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   job_id                      15886 non-null  int64
 1   company_id                  15520 non-null  float64
 2   title                       15886 non-null  str
 3   max_salary                  5521 non-null   float64
 4   med_salary                  981 non-null    float64
 5   min_salary                  5521 non-null   float64
 6   pay_period                  6502 non-null   str
 7   formatted_work_type         15886 non-null  str
 8   location                    15886 non-null  str
 9   applies                     8700 non-null   float64
 10  original_listed_time        15886 non-null  float64
 11  remote_allowed              2340 non-null   float64
 12  views                       13123 non-null  float64
 13  job_posting_url             15886 non-null  str
 14  application_url             9795 non-null   str
 15  application_type            15886 non-null  str
 16  expiry                      15886 non-null  float64
 17  closed_time                 928 non-null    float64
 18  formatted_experience_level  10984 non-null  str
 19  skills_desc                 144 non-null    str
 20  listed_time                 15886 non-null  float64
 21  posting_domain              9044 non-null   str
 22  sponsored                   15886 non-null  int64
 23  work_type                   15886 non-null  str
 24  currency                    6502 non-null   str
 25  compensation_type           6502 non-null   str
dtypes: float64(11), int64(2), str(13)
memory usage: 3.2 MB

In [4]:
df.nunique()

job_id                        15886
company_id                     6030
title                         10956
max_salary                     1314
med_salary                      314
min_salary                     1233
pay_period                        3
formatted_work_type               7
location                       3010
applies                         285
original_listed_time              1
remote_allowed                    1
views                           713
job_posting_url               15886
application_url                8899
application_type                  3
expiry                            3
closed_time                       1
formatted_experience_level        6
skills_desc                     141
listed_time                       1
posting_domain                 1296
sponsored                         2
work_type                         7
currency                          1
compensation_type                 1
dtype: int64

In [5]:
df.isna().sum()

job_id                            0
company_id                      366
title                             0
max_salary                    10365
med_salary                    14905
min_salary                    10365
pay_period                     9384
formatted_work_type               0
location                          0
applies                        7186
original_listed_time              0
remote_allowed                13546
views                          2763
job_posting_url                   0
application_url                6091
application_type                  0
expiry                            0
closed_time                   14958
formatted_experience_level     4902
skills_desc                   15742
listed_time                       0
posting_domain                 6842
sponsored                         0
work_type                         0
currency                       9384
compensation_type              9384
dtype: int64

In [6]:
df = df[['job_id', 
         'company_id', 
         'title', 
         'max_salary', 
         'min_salary', 
         'formatted_work_type', 
         'location', 
         'applies', 
         'remote_allowed', 
         'views', 
         'job_posting_url', 
         'application_url', 
         'application_type', 
         'formatted_experience_level', 
         'sponsored']]
df

,job_id,company_id,title,max_salary,min_salary,formatted_work_type,location,applies,remote_allowed,views,job_posting_url,application_url,application_type,formatted_experience_level,sponsored
0,85008768,NaN,Licensed Insurance Agent,52000.0,45760.0,Full-time,"Chico, CA",NaN,NaN,5.0,https://www.linkedin.com/jobs/view/85008768/?t...,NaN,ComplexOnsiteApply,NaN,1
1,133114754,77766802.0,Sales Manager,NaN,NaN,Full-time,"Santa Clarita, CA",NaN,NaN,NaN,https://www.linkedin.com/jobs/view/133114754/?...,NaN,ComplexOnsiteApply,NaN,0
2,133196985,1089558.0,Model Risk Auditor,NaN,NaN,Contract,"New York, NY",1.0,NaN,17.0,https://www.linkedin.com/jobs/view/133196985/?...,NaN,ComplexOnsiteApply,NaN,0
3,381055942,96654609.0,Business Manager,NaN,NaN,Full-time,"Forney, TX",NaN,NaN,NaN,https://www.linkedin.com/jobs/view/381055942/?...,NaN,ComplexOnsiteApply,NaN,0
4,529257371,1244539.0,NY Studio Assistant,NaN,NaN,Full-time,"New York, NY",NaN,NaN,2.0,https://www.linkedin.com/jobs/view/529257371/?...,NaN,ComplexOnsiteApply,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15881,3701373516,74718032.0,Sanitation Technician,NaN,NaN,Part-time,"West Columbia, SC",NaN,NaN,1.0,https://www.linkedin.com/jobs/view/3701373516/...,https://aspirebakeriescareers.com/job/West-Col...,OffsiteApply,Entry level,0
15882,3701373522,38897.0,Unit Secretary,NaN,NaN,Full-time,"Teaneck, NJ",2.0,NaN,7.0,https://www.linkedin.com/jobs/view/3701373522/...,https://recruiting.ultipro.com/HOL1005HNMC/Job...,OffsiteApply,Entry level,0
15883,3701373523,38897.0,"Radiology Aide, Perdiem",NaN,NaN,Part-time,"Teaneck, NJ",NaN,NaN,3.0,https://www.linkedin.com/jobs/view/3701373523/...,https://recruiting.ultipro.com/HOL1005HNMC/Job...,OffsiteApply,Entry level,0
15884,3701373524,2623.0,MRI Manager,135000.0,110000.0,Full-time,"New York, NY",NaN,NaN,10.0,https://www.linkedin.com/jobs/view/3701373524/...,https://opportunities.columbia.edu/jobs/mri-ma...,OffsiteApply,Mid-Senior level,0
15885,3701373527,84659.0,Area Director of Business Development,NaN,NaN,Full-time,"Vicksburg, MS",2.0,NaN,31.0,https://www.linkedin.com/jobs/view/3701373527/...,NaN,ComplexOnsiteApply,NaN,0

In [7]:
da = df[df.title == 'Data Analyst']

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15886 entries, 0 to 15885
Data columns (total 15 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   job_id                      15886 non-null  int64
 1   company_id                  15520 non-null  float64
 2   title                       15886 non-null  str
 3   max_salary                  5521 non-null   float64
 4   min_salary                  5521 non-null   float64
 5   formatted_work_type         15886 non-null  str
 6   location                    15886 non-null  str
 7   applies                     8700 non-null   float64
 8   remote_allowed              2340 non-null   float64
 9   views                       13123 non-null  float64
 10  job_posting_url             15886 non-null  str
 11  application_url             9795 non-null   str
 12  application_type            15886 non-null  str
 13  formatted_experience_level  10984 non-null  str
 14  sponsored                   15886 non-null  int64
dtypes: float64(6), int64(2), str(7)
memory usage: 1.8 MB

In [9]:
df[['max_salary', 'min_salary', 'applies', 'views']].agg(['mean', 'median', 'std', 'min', 'max'])

          max_salary     min_salary      applies        views
mean    8.833622e+04   62352.218073    22.833103    76.776575
median  8.200000e+04   60000.000000     6.000000    25.000000
std     9.068282e+04   59487.692283    54.892826   167.459105
min     1.000000e+01      10.000000     1.000000     1.000000
max     1.300000e+06  800000.000000  1615.000000  5656.000000

In [10]:
df.to_csv(os.path.join(parent_dir, "cleaned_datasets", "1_job_postings.csv"), index=False)

### Making file#2 (job_skills)

In [11]:
df1 = pd.read_csv(os.path.join(parent_dir, "raw_datasets", "job_skills.csv"))
df2 = pd.read_csv(os.path.join(parent_dir, "raw_datasets", "job_industries.csv"))

In [12]:
merged_df = pd.merge(df1, df2, on='job_id', how='inner')

In [13]:
df1.info()
df2.info()
merged_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 27899 entries, 0 to 27898
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   job_id     27899 non-null  int64
 1   skill_abr  27899 non-null  str
dtypes: int64(1), str(1)
memory usage: 436.1 KB
<class 'pandas.DataFrame'>
RangeIndex: 21993 entries, 0 to 21992
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   job_id       21993 non-null  int64
 1   industry_id  21993 non-null  int64
dtypes: int64(2)
memory usage: 343.8 KB
<class 'pandas.DataFrame'>
RangeIndex: 40088 entries, 0 to 40087
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   job_id       40088 non-null  int64
 1   skill_abr    40088 non-null  str
 2   industry_id  40088 non-null  int64
dtypes: int64(2), str(1)
memory usage: 939.7 KB

In [14]:
merged_df.sample(5)

           job_id skill_abr  industry_id
10397  3693073626        HR           19
27500  3699081782      MGMT           48
33432  3701302760      MRKT           43
15489  3694106782      GENB           31
39131  3701367820       ENG           15

In [15]:
merged_df[merged_df.job_id == 3693049437]

          job_id skill_abr  industry_id
4300  3693049437      SALE           43
4301  3693049437        BD           43

In [16]:
merged_df.to_csv(os.path.join(parent_dir, "cleaned_datasets", "2_job_skills_industry.csv"), index=False)

### Making file#3 (company)

In [17]:
df3_org = pd.read_csv(os.path.join(parent_dir, "raw_datasets", "companies.csv"))
df4 = pd.read_csv(os.path.join(parent_dir, "raw_datasets", "company_industries.csv"))
df5 = pd.read_csv(os.path.join(parent_dir, "raw_datasets", "company_specialities.csv"))
df6 = pd.read_csv(os.path.join(parent_dir, "raw_datasets", "employee_counts.csv"))

In [19]:
df3 = df3_org[['company_id', 'company_name', 'city', 'state', 'country', 'url']]

In [20]:
df4.info(), df5.info(), df6.info()

<class 'pandas.DataFrame'>
RangeIndex: 15880 entries, 0 to 15879
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   company_id  15880 non-null  int64
 1   industry    15880 non-null  str
dtypes: int64(1), str(1)
memory usage: 248.3 KB
<class 'pandas.DataFrame'>
RangeIndex: 128355 entries, 0 to 128354
Data columns (total 2 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   company_id  128355 non-null  int64
 1   speciality  128355 non-null  str
dtypes: int64(1), str(1)
memory usage: 2.0 MB
<class 'pandas.DataFrame'>
RangeIndex: 15907 entries, 0 to 15906
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   company_id      15907 non-null  int64
 1   employee_count  15907 non-null  int64
 2   follower_count  15907 non-null  int64
 3   time_recorded   15907 non-null  float64
dtypes: float64(1), int64(3)
memory usage: 497.2 KB

(None, None, None)

In [21]:
df4 = df4.drop_duplicates(subset='company_id', keep='first')
df5 = df5.drop_duplicates(subset='company_id', keep='first')
df6 = df6.drop_duplicates(subset='company_id', keep='first')

merged_df1_beta = pd.merge(df4, df5, on='company_id', how='inner').merge(df6, on='company_id', how='inner')
merged_df1 = pd.merge(df3_org[['company_id', 'company_size']], merged_df1_beta, on='company_id', how='inner')

merged_df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 4452 entries, 0 to 4451
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   company_id      4452 non-null   int64
 1   company_size    4146 non-null   float64
 2   industry        4452 non-null   str
 3   speciality      4452 non-null   str
 4   employee_count  4452 non-null   int64
 5   follower_count  4452 non-null   int64
 6   time_recorded   4452 non-null   float64
dtypes: float64(2), int64(3), str(2)
memory usage: 243.6 KB

In [22]:
df3.to_csv(os.path.join(parent_dir, "cleaned_datasets", "3_companies.csv"), index=False)
merged_df1.to_csv(os.path.join(parent_dir, "cleaned_datasets", "4_company_details.csv"), index=False)